# NumPy

## 1. Introduction to NumPy

NumPy (Numerical Python) is a powerful, open-source library for numerical computing in Python. It provides support for arrays, matrices, and a wide range of mathematical functions, making it essential for scientific computing.

### 1.1 Key Features:
- Efficient multi-dimensional array object (ndarray): Supports large, multi-dimensional arrays and matrices.
- Mathematical functions for operations on arrays: Provides a large library of high-level mathematical functions to operate on these arrays.
- Tools for integrating C/C++ and Fortran code: Useful for performance-critical applications.
- Random number capabilities: Functions for generating random numbers and random sampling.

## 2. Installation
To install NumPy, use the following command in your terminal:

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


## 3. Importing NumPy
You typically import NumPy using the alias np for convenience:

In [3]:
import numpy as np

## 4. Creating Arrays
### 4.1. Creating Arrays from Lists
You can create an array from a Python list using np.array().

In [4]:
array = np.array([1, 2, 3, 4])

### 4.2. Creating Multi-dimensional Arrays
Create multi-dimensional arrays (e.g., matrices) by passing nested lists to np.array().

In [5]:
array_2d = np.array([[1, 2], [3, 4]])

### 4.3. Using arange and linspace
- np.arange(start, stop, step): Creates arrays with regularly spaced values

In [8]:
arr = np.arange(0, 10, 2)  
arr

array([0, 2, 4, 6, 8])

- np.linspace(start, stop, num): Creates arrays with evenly spaced values between a start and end value.

In [9]:
linspace_arr = np.linspace(0, 1, 5)
linspace_arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### 4.4. Creating Special Arrays
- Zeros Array: Creates an array filled with zeros

In [10]:
zeros = np.zeros((3, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

- Ones Array: Creates an array filled with ones

In [11]:
ones = np.ones((2, 2))
ones

array([[1., 1.],
       [1., 1.]])

- Identity Matrix: Creates an identity matrix

In [12]:
identity = np.eye(3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 5. Array Attributes and Methods
### 5.1. Attributes
- shape: Returns a tuple indicating the size of the array in each dimension

In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape) 

(2, 3)


- dtype: Data type of the array's elements.

In [15]:
print(arr.dtype)

int32


- size: Total number of elements

In [17]:
print(arr.size)  

6


- ndim: Number of dimensions

In [18]:
print(arr.ndim)  

2


### 5.2. Methods
- reshape(): Change the shape of an array without changing its data

In [23]:
reshaped = arr.reshape((3, 2))
reshaped

array([[1, 2],
       [3, 4],
       [5, 6]])

- flatten(): Flatten a multi-dimensional array to a 1D array

In [20]:
flattened = arr.flatten()
flattened

array([1, 2, 3, 4, 5, 6])

- transpose(): Transpose the array (swap axes)

In [21]:
transposed = arr.transpose()
transposed

array([[1, 4],
       [2, 5],
       [3, 6]])

## 6. Array Indexing and Slicing
### 6.1. Indexing
Access elements using square brackets:

In [25]:
element = arr[1, 2]  # Accessing element at second row, third column
element

6

### 6.2. Slicing
Slicing syntax: start:stop:step

In [26]:
slice_ = arr[0, 1:]  # Slicing first row from the second element
slice_

array([2, 3])

## 7. Array Operations
### 7.1. Arithmetic Operations
NumPy allows element-wise arithmetic operations between arrays.

In [27]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)  
print(a * b)  

[5 7 9]
[ 4 10 18]


### 7.2. Universal Functions (ufuncs)
Universal functions operate element-wise on an array.

In [28]:
print(np.sqrt(a)) 
print(np.exp(a))   

[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]


## 8. Broadcasting
Broadcasting allows operations on arrays of different shapes. Smaller arrays are "broadcast" over larger ones to perform element-wise operations.

In [29]:
a = np.array([[1], [2], [3]])
b = np.array([4, 5, 6])
print(a + b) 

[[5 6 7]
 [6 7 8]
 [7 8 9]]


## 9. Linear Algebra
### 9.1. Dot Product
Calculate the dot product of two arrays

In [32]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
dot_product = np.dot(a, b)
dot_product

array([[19, 22],
       [43, 50]])

### 9.2. Matrix Multiplication
Perform matrix multiplication using matmul.

In [34]:
mat_mult = np.matmul(a, b)
mat_mult

array([[19, 22],
       [43, 50]])

### 9.3. Determinant and Inverse
- Determinant: Calculate the determinant of an array

In [35]:
det = np.linalg.det(a)
det

-2.0000000000000004

- Inverse: Calculate the inverse of an array

In [36]:
inverse = np.linalg.inv(a)
inverse

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

## 10. Random Number Generation
### 10.1. Random Arrays
Generate arrays of random numbers.

- Uniformly distributed over [0, 1)

In [37]:
rand_arr = np.random.rand(3, 3)
rand_arr

array([[0.20571234, 0.19949621, 0.66304829],
       [0.82379021, 0.30377801, 0.59364409],
       [0.31964465, 0.41629306, 0.35717136]])

- Random integers between specified range

In [39]:
rand_int = np.random.randint(0, 10, (3, 3))
rand_int

array([[9, 3, 7],
       [9, 4, 2],
       [3, 7, 5]])

### 10.2. Seed
Set the seed for reproducibility of random numbers.

In [40]:
np.random.seed(42)  # Set the seed for reproducibility

## 11. Useful Functions
### 11.1. Summation and Product
- Sum: Sum of array elements

In [41]:
sum_ = np.sum(arr)
sum_

21

- Product: Product of array elements

In [42]:
prod = np.prod(arr)
prod

720

### 11.2. Minimum and Maximum
- Minimum: Find the minimum element

In [43]:
min_ = np.min(arr)
min_

1

- Maximum: Find the maximum elemen

In [44]:
max_ = np.max(arr)
max_

6

### 11.3. Mean, Median, Standard Deviation
- Mean: Calculate the mean of elements

In [45]:
mean = np.mean(arr)
mean

3.5

- Median: Calculate the median of elements

In [46]:
median = np.median(arr)

In [47]:
median

3.5

- Standard Deviation: Calculate the standard deviation.

In [48]:
std_dev = np.std(arr)

In [49]:
std_dev

1.707825127659933

## 12. Handling Missing Data
### 12.1. Using NaN
NumPy provides NaN (Not a Number) to represent missing values

In [50]:
arr_with_nan = np.array([1, 2, np.nan, 4])
arr_with_nan

array([ 1.,  2., nan,  4.])

### 12.2. Checking for NaN
Check for NaN values using np.isnan().

In [51]:
nan_check = np.isnan(arr_with_nan)
nan_check

array([False, False,  True, False])

### 12.3. Filling NaN
Replace NaN values using np.nan_to_num().

In [52]:
filled_arr = np.nan_to_num(arr_with_nan)
filled_arr

array([1., 2., 0., 4.])